### ISSUE TITLE
aws_functions bug

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban-toolbox#103]
https://github.com/vanvalenlab/caliban-toolbox/blob/64c120dc01e691f1ddf093b42837c2eed712ca23/caliban_toolbox/aws_functions.py#L129

`aws_path` got re-renamed to `img_path` here and should be corrected to `aws_path`. Looks like `img` in the subsequent exception is not initialized anywhere either.

**Comment by ngreenwald** [comment]
@willgraf, do you have any suggestions for how we can add these functions that depend on either AWS or Figure8 to the test suite?

**Comment by willgraf** [comment]
You can mock their responses with `pytest-mock` or (if youre using `requests`) `requests_mock`.  They allow you to override the 3rd party function call and return a specific response.
