### ISSUE TITLE
Add preview of overlapping chopper to pre-annotation

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban-toolbox#23]
Currently, users of the pipeline can chop up an image into overlapping image pieces, with parameters for how many pieces in x and y directions, and the percentage of overlap between pieces. The overlapping chopper should have a preview section, like the contrast adjustment steps, where users can see what image pieces would look like before using those variables to process all of the images in a set. Like the contrast adjustment preview, variables should be adjustable with a widget.

The preview image should be the image of interest overlaid with lines to indicate the edges of image pieces. Regions of overlap should be distinguished from non-overlapping regions in the full image. This will allow users to choose an appropriate image size for annotators and adjust the redundancy of annotations (by changing overlap percentage) if needed.

**Comment by ngreenwald** [comment]
The jupyter notebook has a first pass at this. It currently works after you've already chopped everything, and doesn't distinguish between overlapping and non-overlapping regions. Do you have an idea about a good way to visualize the difference between the independent vs overlapping regions of the chop?

**Comment by ngreenwald** [comment]
I just pushed a first pass at the implementation we discussed last week. It's in the 2D upload notebook. Take a look when you have a chance and let me know what you think
