### ISSUE TITLE
Add image downsampling option to pipeline

### ISSUE THREAD

**Issue by geneva-miller** [vanvalenlab/caliban-toolbox#24]
Images can be downsampled to make them into sizes that are easier to handle with model training and prediction. If a user intends to downsample images from their original size, it is probably easiest to do this step at the beginning of the pipeline. Downsampled images don't have as much detail, which can sometimes make image features more difficult for annotators to distinguish clearly. However, downsampled images also have fewer pixels, which can actually speed up annotations (and reduce costs!).

If downsampling is implemented in the pre-processing notebooks, it should take place before contrast adjustment of images. Alternatively, it could take place in a notebook separate from the pipeline. If separate from pipeline, it could be a standalone notebook, or a notebook for image file prep (split out frames and/or channels from .tif files, rescale images, one or two other things as needed), or a notebook that is a general collection of image manipulation functions. It could have redundancy and exist in more than one place! But it definitely should exist to be used in conjunction with pre-annotation.

**Comment by ngreenwald** [comment]
Is this still something you're interested in?

**Comment by ngreenwald** [comment]
Hey @geneva-miller, my sense is that this is going to be migrated to the build.py functionality. 
@MekWarrior, where are the build.py files going to be maintained? Within deepcell-tf? If so we can probably close this.
