### ISSUE TITLE
clean up test suite

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban-toolbox#40]
There are currently a lot of test functions that don't appear to be relevant for what the toolbox currently does. We should figure out what the scope of the this repo is going to be moving forward, and then clean up all of the superfluous testing so that we can have the builds start passing the checks. 

It looks like one of the current problems is the "deprecated" folder. I think we should just remove this.

**Comment by ngreenwald** [comment]
Hey @MekWarrior and @willgraf, Geneva said you two would be the people to ask about cleaning up some of the old files in here. TravisCI is currently failing for a number of reasons on the feature/caliban_pipeline branch, but one of the reasons is the files in the deprecated folder are referencing modules that don't exist anymore.  Do we still need to keep the deprecated folder?

There's also a fair number of other tests that are failing, but most of them don't appear to be that relevant for what the toolbox actually does now. I don't want to start removing stuff willy-nilly, but it would be good to go through those at some point to decide what's still needed and what isn't so that our builds can start passing again. 

Finally, I also wrote a first pass at a set of test functions for the new npz-based implementation of the pipeline on the feature/caliban_pipeline branch (tests/deepcell_toolbox/npz_test.py), it would be great to get some feedback on those eventually since I don't have much experience writing tests.

**Comment by willgraf** [comment]
I think it is very unlikely we need anything in the deprecated folder.  We can always go back in the git history to find them.

I have not looked at this project in quite a while, so I am not familiar with what it does now vs. what it used to do.

In regard to testing, I can look through the changes when they're ready and provide some feedback. In the meantime, I like to use `pytest-cov` to measure how many lines of each file I am actually testing.

**Comment by ngreenwald** [comment]
Got it, thanks! @geneva-miller, is it fair to assume that for the utils functions, if they don't appear anywhere in the repository instead for their definition and in the test functions they can be safely removed?

i.e., anything that is required for the current version of the toolbox will be called at least once somewhere in the notebooks or other code?

**Comment by geneva-miller** [comment]
Yes, I think that's fair to assume. We can always add things back if it turns out we need them somewhere.

**Comment by ngreenwald** [comment]
Hi @willgraf, the build is now passing on python 3.5 but failing on 3.6. 
The error that's getting raised is below, which to me appears quite mysterious. 

```
python -m pytest --cov=deepcell_toolbox deepcell_toolbox tests
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pytest.py", line 13, in <module>
from _pytest.fixtures import fixture, yield_fixture

  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/fixtures.py", line 839, in <module>
    class FixtureFunctionMarker(object):

  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/fixtures.py", line 841, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))

TypeError: attrib() got an unexpected keyword argument 'convert'

The command "python -m pytest --cov=deepcell_toolbox deepcell_toolbox tests" exited with 1.
```

link is here:
https://github.com/vanvalenlab/deepcell-toolbox/runs/425772822

**Comment by willgraf** [comment]
[It sounds like this might be a pytest versioning issue](https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert).

Maybe try removing the pytest-cov version pinning or try pinning `pytest==5.2.0`.
