### ISSUE TITLE
What is this repository for?

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/caliban-toolbox#48]
It seems to be a repo for any/and all data processing functions?

If so, I am working on a standalone repository for pre/post-processing functions commonly used for `deepcell-tf` models. (think a repo for doing mibi postprocessing or nuclear segmentation post-processing).  I want to publish these as a pip package, and install it in some commonly used places, like `deepcell-tf` and the `kiosk-redis-consumer`.  (This is sort of a mirror of `deepcell-tracking`)

Should these be added to the `deepcell-toolbox`?  Or should my new repo be standalone?

**Comment by geneva-miller** [comment]
I think of it as being a repo more for creating and working with datasets. So the main focus right now is on pre- and post-processing for online annotation. I think this will also be where you would process files pre- and post-caliban, whether that be the browser or desktop version. 

I think your new repo should be separate from this, but I don't have strong feelings about it.

**Comment by ngreenwald** [comment]
All of the new development for deepcell-toolbox is currently going on in the feature/caliban_pipeline branch of deepcell-toolbox. I think that gives a better idea for the long-term vision for this repo, which is exactly what Geneva mentioned.

Basically, any processing that needs to happen before it gets labeled with Caliban, and then whatever cleanup needs to happen post-caliban

**Comment by willgraf** [comment]
I am considering renaming this repository something more...clear.  Maybe `caliban-toolbox` instead, since it seems to pertain specifically to up- and down-stream utilities for Caliban. (Plus, then maybe I can re-cycle the `deepcell-toolbox` for the repository I am building)

Thoughts on the refactor? Is this repo being used in any down-strem dependencies where refactoring may cause issues?

**Comment by ngreenwald** [comment]
Yeah, the functionality has definitely shifted from when it was originally named. Currently this is not being imported anywhere else, I don't think a name change would cause any issues

**Comment by willgraf** [comment]
OK! I will be refactoring this repository to `caliban-toolbox`. Please change your local `.git/config` files to reflect this change.

**Comment by willgraf** [comment]
@geneva-miller  @ngreenwald  I've now merged in the PRs and updated everything to caliban-toolbox.

I'm closing this issue. Thanks for the help!
