### ISSUE TITLE
least confusing nomenclature

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban-toolbox#61]
As I'm going through and standardizing the code that does data reshaping and resizing, I'd like to use standard names for the dimensions of these arrays that are consistent across the repo and not confusing. 

If you guys have thoughts on names for the things below, please let me know. 

- the dimension that holds images from different physical locations in the sample. For MIBI data, this would be each image, as it was acquired in a different location. For timeseries/3D data, this would be different movies/stacks that are stored together on this axis. For MIBI data we use points. The more general microscopy term might be FOV (field of view). Could also use image or sample.

- the dimension that holds images acquired in the same 2D location, either separated in t (for timeseries) or z (for 3D). This is often referred to as a slice/stack in the current code, or a movie. 

- the dimension that holds a subset of the above t/z data, when it has been shortened to make smaller Figure8 jobs. This is sometimes referred to as a montage. 

- the dimension that holds the y dimension of the 2D image. I've been calling this rows to distinguish from the x/y raw/labeled dichotomy

- the dimension that holds the x dimension of the 2D image. I've been calling this cols to distinguish from the x/y raw/labeled dichotomy

- the dimension that holds a subset of the above x/y data, when it has been subsetted to make smaller figure8 jobs. This is called a crop. I'm happy with this one.

**Comment by geneva-miller** [comment]
One thing that's jumped out at me is the use of "montage" which has a different meaning for us than "subset of movie in t/z". While we have used montages before for 3D data, making a montage from a movie is a type of reshaping that I don't think we should use going forward with Caliban.

Example: 
![image](https://user-images.githubusercontent.com/45578681/76716247-ce704280-66ec-11ea-99c0-211cc9f1dd22.png)

Frames, or pieces of frames, are placed next to each other so t/z data can be included in just one 2D image.

I'm not sure how to distinguish stacks/movies from partial stacks/movies but I would steer clear of "montage" to avoid confusion. @MekWarrior do you have opinions about this one?

**Comment by ngreenwald** [comment]
Got it. I'm currently leaning towards stacks to describe the entire z/t stack of data, and slice to denote a subset of that data
