### ISSUE TITLE
get_image

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/caliban-toolbox#7]
get image assumes the data is already in the correct format with the correct number of dimensions. We should squeeze out the batch dimension in this function to ensure this is the case.

**Comment by MekWarrior** [comment]
get_image also makes assumption as to data type. This should agree with the function used in deepcell-tf and the Kiosk (i.e. we should decide on a set datatype and standardize everything to it)

**Comment by ngreenwald** [comment]
This will be resolved with unified data loader, which will handle all i/o
