### ISSUE TITLE
ModuleNotFoundError: No module named 'caliban_toolbox.utils.io_utils'

### ISSUE THREAD

**Issue by epao111** [vanvalenlab/caliban-toolbox#77]
Tried running the first cell of the Figure8 upload script and got this error. I have current version of the folders.

**Comment by ngreenwald** [comment]
Yeah, it got changed to utils instead of io_utils. I'm going to be going back through this over the weekend updating it with some of the changes Geneva and I have talked about, I think it's worth waiting till then.
